# https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
# But note the data will be different depending on which node you run
# It is not synchronized between worker1 and worker2
apiVersion: v1
kind: Pod
metadata:
  name: volume-claim-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: foo
      mountPath: /tmp/myvol
  volumes:
    - name: foo
      persistentVolumeClaim:
        claimName: pv-claim
