apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: web-cnt
          image: philip11/java-app-kube:v1
          imagePullPolicy: Always
# just documentation. only useful / needs to be correct for container->container connection on same pod
#          ports:
#            - containerPort: 8090
