apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: c1
      image: alpine
      volumeMounts:
        - name: varlog
          mountPath: /var/log
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true;
          do
            echo "C1" `date`
            echo "Hi from C1" >> /var/log/log.txt
            sleep 1
          done
    - name: c2
      image: alpine
      volumeMounts:
        - name: varlog
          mountPath: /var/log
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true;
          do
            echo "C2" `date`
            echo "Hi from C2" >> /var/log/log.txt
            sleep 1
          done
  volumes:
    - name: varlog
      emptyDir: {}
