apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myset
spec:
  serviceName: mysvc-h
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: c1
          image: nginx
          imagePullPolicy: IfNotPresent

