# headless service does not have its own ip and does not load balance
# just provide stable dns for each pod
# set spec.clusterIP: None
apiVersion: v1
kind: Service
metadata:
  name: mysvc-h
spec:
  clusterIP: None
  selector:
    app: myapp
  ports:
  - port: 80

