# Example of sending everything to one service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: myapp-svc
      port:
        number: 80

